site_name: André Madeira Cortes
site_url: https://bambalaam.me
site_author: André Madeira Cortes
site_description: Your personal website and blog

theme:
  name: material
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false

# Navigation
nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md
  - Now: now.md

plugins:
  - search
  - blog:
      post_url_date_format: yyyy

# Extensions
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg